# ML-04 — Search Intelligence Data Contract

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/yyashkumarsharma23-max/flyrank-internship-ml/blob/main/work/notebooks/w03_data_contract.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

In [2]:
import duckdb
from datasets import load_dataset
from google.colab import userdata

# Loading the Dataset
my_token = userdata.get('HF_TOKEN1')
print("Loading dataset metadata...")
dataset = load_dataset("FlyRank/internship-warehouse", "fact_content_daily_performance", split="train", token=my_token)


fact_content_daily_performance = dataset.data.table

print("Dataset is ready for lightning-fast queries!")

Loading dataset metadata...

README.md:   0%|          | 0.00/3.04k [00:00<?, ?B/s]

Resolving data files:   0%|          | 0/18 [00:00<?, ?it/s]

Downloading data:   0%|          | 0/18 [00:00<?, ?files/s]

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  134MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 19.6kB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 3.29MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 1.45MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  124MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 2.62MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 90.3MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 7.12MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 8.93MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 21.6MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 89.0MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  624kB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 4.41MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 86.2MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 3.22MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 72.0MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  149MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  146MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/78835655 [00:00<?, ? examples/s]

Loading dataset shards:   0%|          | 0/39 [00:00<?, ?it/s]

Dataset is ready for lightning-fast queries!

## 1. Unit of analysis + time window

*One row = one what, over which dates? State it, then verify it below.*

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

**Grain:** One row represents the search and analytics performance of a single content piece on one specific day.

**Time Window:** I am using a mid-panel month for my training data, the month of March 2026 (from 2026-03-01 to 2026-03-31).

In [4]:
query1 = """
SELECT
    MIN(date) AS start_date,
    MAX(date) AS end_date,
    COUNT(*) AS total_rows
FROM fact_content_daily_performance
WHERE date >= '2026-03-01' AND date <= '2026-03-31'
"""
display(duckdb.sql("DESCRIBE fact_content_daily_performance").df())

                 column_name column_type null   key default extra
0                report_date        DATE  YES  None    None  None
1             client_hash_id     VARCHAR  YES  None    None  None
2            content_hash_id     VARCHAR  YES  None    None  None
3             client_has_gsc     BOOLEAN  YES  None    None  None
4             client_has_ga4     BOOLEAN  YES  None    None  None
5         gsc_data_available     BOOLEAN  YES  None    None  None
6         ga4_data_available     BOOLEAN  YES  None    None  None
7            gsc_impressions      BIGINT  YES  None    None  None
8                 gsc_clicks      BIGINT  YES  None    None  None
9           gsc_sum_position      BIGINT  YES  None    None  None
10          gsc_avg_position      DOUBLE  YES  None    None  None
11             ga4_pageviews      BIGINT  YES  None    None  None
12              ga4_sessions      BIGINT  YES  None    None  None
13                 ga4_users      BIGINT  YES  None    None  None
14      ga4_engaged_sessions      BIGINT  YES  None    None  None
15  ga4_total_engagement_sec      BIGINT  YES  None    None  None
16          sessions_organic      BIGINT  YES  None    None  None
17           sessions_direct      BIGINT  YES  None    None  None
18         sessions_referral      BIGINT  YES  None    None  None
19           sessions_social      BIGINT  YES  None    None  None
20             sessions_paid      BIGINT  YES  None    None  None
21               sessions_ai      BIGINT  YES  None    None  None
22                ai_chatgpt      BIGINT  YES  None    None  None
23             ai_perplexity      BIGINT  YES  None    None  None
24                 ai_gemini      BIGINT  YES  None    None  None
25                ai_copilot      BIGINT  YES  None    None  None
26                 ai_claude      BIGINT  YES  None    None  None
27                   ai_meta      BIGINT  YES  None    None  None
28                  ai_other      BIGINT  YES  None    None  None
29             scroll_events      BIGINT  YES  None    None  None

## 2. Fields: feature / label / context / excluded

*Sort every field you plan to touch into these four buckets. Excluded needs a why.*

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

1. **Context (Metadata/Identifiers):**

date, client_hash_id, content_hash_id

Why: Context refers only in the idetification of rows. We cannot use Machine Learning models here.

2. **Label (Target Variable):**

clicks

Why: This refers to a metric in which we can analyze or pedict data outcomes based on previous values.

3. **Features (Inputs):**

impressions: Knowable at the decision moment because Google shows the URL before a user can click on it.

position: Knowable at the decision moment because ranking happens before the user's click action.

4. **Excluded:**

ctr (Click-Through Rate): Excluded because it is directly calculated from clicks (our label). Using it would cause data leakage.

Rows with impressions = 0: Excluded because if a page wasn't seen at all, predicting clicks on it is useless and will skew the data.

In [6]:
query2 = """
SELECT
    report_date, client_hash_id, content_hash_id,  -- Context
    gsc_impressions, gsc_avg_position,             -- Features
    gsc_clicks                                     -- Label
FROM fact_content_daily_performance
WHERE gsc_impressions > 0
LIMIT 5
"""
display(duckdb.sql(query2).df())

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,report_date,client_hash_id,content_hash_id,gsc_impressions,gsc_avg_position,gsc_clicks
0,2025-01-27,client_9958f0a7ae1df715,content_3b70a18ea133b2bb,30,3.833333,0
1,2025-01-27,client_9958f0a7ae1df715,content_fe8e8155ce1d47a2,5,71.600000,0
2,2025-01-27,client_9958f0a7ae1df715,content_b4462a1b90640058,1,34.000000,0
3,2025-01-27,client_9958f0a7ae1df715,content_c899aef92518c714,6,23.333333,0
4,2025-01-27,client_9958f0a7ae1df715,content_c7c1d2e68d9d0964,5,17.800000,0

## 3. Verify it with queries (grain, counts, missing values, windows)

*Every claim above gets a query cell here. A contract claim without a query next to it is a guess.*

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

**Claim 1: Window**
The data should only contain records for our target window: March 2026. The minimum date should be '2026-03-01' and the maximum date should be '2026-03-31'.

In [7]:
query_window = """
SELECT
    MIN(report_date) AS min_date,
    MAX(report_date) AS max_date
FROM fact_content_daily_performance
WHERE report_date >= '2026-03-01' AND report_date <= '2026-03-31'
"""
display(duckdb.sql(query_window).df())

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

    min_date   max_date
0 2026-03-01 2026-03-31

**Claim 2: Missing Values**
There should be zero NULL values in our core context, feature, and label columns within this time window. If gsc_impressions or gsc_clicks are NULL, our ML model will fail to train.

In [8]:
query_missing = """
SELECT
    SUM(CASE WHEN report_date IS NULL THEN 1 ELSE 0 END) AS null_dates,
    SUM(CASE WHEN content_hash_id IS NULL THEN 1 ELSE 0 END) AS null_content,
    SUM(CASE WHEN gsc_impressions IS NULL THEN 1 ELSE 0 END) AS null_impressions,
    SUM(CASE WHEN gsc_clicks IS NULL THEN 1 ELSE 0 END) AS null_clicks
FROM fact_content_daily_performance
WHERE report_date >= '2026-03-01' AND report_date <= '2026-03-31'
"""
display(duckdb.sql(query_missing).df())

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   null_dates  null_content  null_impressions  null_clicks
0         0.0           0.0               0.0          0.0

**Claim 3: Grain**
The grain of this dataset is Daily per Content per Client. This means the combination of (report_date, client_hash_id, content_hash_id) must be strictly unique. There should be no duplicate rows for the same content on the same day.

In [9]:
query_grain = """
SELECT
    report_date,
    client_hash_id,
    content_hash_id,
    COUNT(*) as duplicate_count
FROM fact_content_daily_performance
WHERE report_date >= '2026-03-01' AND report_date <= '2026-03-31'
GROUP BY report_date, client_hash_id, content_hash_id
HAVING COUNT(*) > 1
"""
display(duckdb.sql(query_grain).df())

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Empty DataFrame
Columns: [report_date, client_hash_id, content_hash_id, duplicate_count]
Index: []

**Claim 4: Counts & Logic**

We need a count of total rows vs. rows valid for training (where gsc_impressions > 0).

Logically, a page cannot have more clicks than impressions. Rows violating this are invalid.

In [10]:
query_counts = """
SELECT
    COUNT(*) AS total_raw_rows,
    SUM(CASE WHEN gsc_impressions > 0 THEN 1 ELSE 0 END) AS valid_training_rows,
    SUM(CASE WHEN gsc_clicks > gsc_impressions THEN 1 ELSE 0 END) AS illogical_rows
FROM fact_content_daily_performance
WHERE report_date >= '2026-03-01' AND report_date <= '2026-03-31'
"""
display(duckdb.sql(query_counts).df())

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   total_raw_rows  valid_training_rows  illogical_rows
0         9841378            3611061.0             0.0

## 4. Data limits

*What can this data never tell you? Unbalanced history, GSC-only early rows, window overlaps.*

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

**Unbalanced History:** Every client does not have the same amount of data. Some big clients might have thousands of pages and daily records, while smaller clients might only have a few. If we train blindly, the ML model will become biased toward the top 2-3 big clients and perform poorly on smaller ones.

**GSC-only vs GA4 mismatch:** FlyRank combines Google Search Console (GSC) and Google Analytics 4 (GA4). However, not all rows have both. Some clients or older dates might only have GSC data (gsc_data_available = True) but no GA4 data (ga4_data_available = False). We cannot rely on GA4 metrics (like sessions or bounce rate) for all rows.

**Window Overlaps/Sparsity:** We cannot assume every URL gets traffic every single day. There will be gaps (missing days) for specific content_hash_ids if they received 0 impressions, meaning time-series models (like ARIMA or LSTMs) will struggle with broken daily sequences.

In [11]:
# Query 1: Proving Unbalanced History

query_unbalanced = """
SELECT
    client_hash_id,
    COUNT(*) AS total_rows
FROM fact_content_daily_performance
WHERE report_date >= '2026-03-01' AND report_date <= '2026-03-31'
GROUP BY client_hash_id
ORDER BY total_rows DESC
LIMIT 5
"""

# Query 2: Proving GSC-only rows (Missing GA4 data)

query_gsc_ga4 = """
SELECT
    SUM(CASE WHEN gsc_data_available = true THEN 1 ELSE 0 END) AS total_gsc_rows,
    SUM(CASE WHEN ga4_data_available = true THEN 1 ELSE 0 END) AS total_ga4_rows,
    SUM(CASE WHEN gsc_data_available = true AND ga4_data_available = false THEN 1 ELSE 0 END) AS gsc_only_rows
FROM fact_content_daily_performance
WHERE report_date >= '2026-03-01' AND report_date <= '2026-03-31'
"""

print("--- Limitation 1: Unbalanced History (Top 5 Clients dominate the dataset) ---")
display(duckdb.sql(query_unbalanced).df())

print("\n--- Limitation 2: Data Availability Mismatch (GSC vs GA4) ---")
display(duckdb.sql(query_gsc_ga4).df())

--- Limitation 1: Unbalanced History (Top 5 Clients dominate the dataset) ---

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

            client_hash_id  total_rows
0  client_625b6439094e23e4      988497
1  client_3ffa76342f366962      904847
2  client_73cda7b4e4f265ea      869640
3  client_08a6a72ff48e62c0      851275
4  client_62f4a7e64f5e0096      756660

--- Limitation 2: Data Availability Mismatch (GSC vs GA4) ---

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   total_gsc_rows  total_ga4_rows  gsc_only_rows
0       3611061.0        413966.0      1718348.0

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.